function downloadPDF() {
    if (!CURRENT) return;

    const win = window.open("", "_blank");
    win.document.write(`
    <html>
    <head>
      <title>Hasil Ujian</title>
      <style>
        body { font-family: Arial; padding: 40px; }
        h1 { color: #4f46e5; }
        hr { margin: 20px 0; }
      </style>
    </head>
    <body>
      <h1>Hasil Evaluasi Ujian Bahasa Inggris</h1>
      <p><b>Nama:</b> ${CURRENT.nama}</p>
      <p><b>Email:</b> ${CURRENT.email}</p>
      <p><b>Nilai:</b> ${CURRENT.nilai}</p>
      <hr>

      ${CURRENT.detail.filter(s => !s.benar).map(s => `
        <p><b>Soal ${s.no}</b></p>
        <p>${s.soal}</p>
        <p>Jawaban kamu: ❌ ${s.jawaban_peserta}</p>
        <p>Jawaban benar: ✅ ${s.jawaban_benar}</p>
        <hr>
      `).join("")}

      <small>Generated by CiwAI • ${new Date().toLocaleString()}</small>
    </body>
    </html>
  `);

    win.document.close();
    win.print();
}
